name = "CEDAC"
uuid = "ca6c2ff3-86a4-4ddc-b37e-64ea1285e4c7"
authors = ["Michael Jin <mikhail.jin@gmail.com>"]
version = "0.9.0"

[deps]
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"
NVIDIALibraries = "455bb3cc-869f-42f8-aad9-fcdd684af481"

[compat]
julia = "1"
